name: CMake

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout@v2

jobs:
  build_centos7:
    container: kreisl/rootcpp17
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: source /opt/rh/devtoolset-8/enable && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAnalysisTreeQA_BUILD_TESTS=ON -DAnalysisTreeQA_BUNDLED_AT=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        run: cd ${{github.workspace}}/build && ctest -C ${{env.BUILD_TYPE}}
        
  build_fedora35:
    container: rootproject/root:6.24.06-fedora35
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAnalysisTreeQA_BUILD_TESTS=ON -DAnalysisTreeQA_BUNDLED_AT=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: cd ${{github.workspace}}/build && ctest -C ${{env.BUILD_TYPE}}

  build_fedora34:
    container: rootproject/root:6.22.08-fedora34
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAnalysisTreeQA_BUILD_TESTS=ON -DAnalysisTreeQA_BUNDLED_AT=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        run: cd ${{github.workspace}}/build && ctest -C ${{env.BUILD_TYPE}}
        
        
